### ISSUE TITLE
35C3 Lightning Talk

### ISSUE THREAD

**Issue by Wikinaut** [rugk/offline-qr-code-35c3#1]
here's the direct link to the Lightning Talk on 28.12.2018: https://media.ccc.de/v/35c3-9566-lightning_talks_day_2#t=6331

**Comment by rugk** [comment]
Yeah, thanks. Let's just not overload the title, so I shortened it a little…

Also I guess everyone in this issue tracker is already aware of the talk/the content, I presented… :wink:

**Comment by rugk** [comment]
Ahh… thought this was the main issue tracker… :smile: Anyway, yeah, …

**Comment by Wikinaut** [comment]
Dachte, Du packst das evtl. ins README.md
